import {
  Congregation,
  UserProfile,
  PreachingPlace,
  Territory,
  WeeklyAssignment,
  PublicPreachingPlace,
  PublicPreachingAssignment,
} from '../types';

export const DEMO_CONGREGATION: Congregation = {
  id: 'cong-demo-01',
  name: 'Congregación El Roble',
  circuit: 'SV-03',
  timezone: 'America/El_Salvador',
  createdAt: '2026-01-01T08:00:00Z',
  createdBy: 'user-demo-coord',
};

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user-demo-coord',
    congregationId: 'cong-demo-01',
    firstName: 'Carlos',
    lastName: 'López',
    fullName: 'Carlos López',
    email: 'carlos.lopez@demo.org',
    role: 'COORDINADOR',
    canLeadPreaching: true,
    canPublicPreaching: true,
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'user-demo-super',
    congregationId: 'cong-demo-01',
    firstName: 'José',
    lastName: 'Martínez',
    fullName: 'José Martínez',
    email: 'jose.martinez@demo.org',
    role: 'SUPERINTENDENTE_DE_SERVICIO',
    canLeadPreaching: true,
    canPublicPreaching: true,
    active: true,
    createdAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'user-demo-pub1',
    congregationId: 'cong-demo-01',
    firstName: 'Juan',
    lastName: 'Pérez',
    fullName: 'Juan Pérez',
    email: 'juan.perez@demo.org',
    role: 'PUBLICADOR',
    canLeadPreaching: true,
    canPublicPreaching: true,
    active: true,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'user-demo-pub2',
    congregationId: 'cong-demo-01',
    firstName: 'Pedro',
    lastName: 'Hernández',
    fullName: 'Pedro Hernández',
    email: 'pedro.hernandez@demo.org',
    role: 'PUBLICADOR',
    canLeadPreaching: false,
    canPublicPreaching: true,
    active: true,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'user-demo-pub3',
    congregationId: 'cong-demo-01',
    firstName: 'David',
    lastName: 'Gómez',
    fullName: 'David Gómez',
    email: 'david.gomez@demo.org',
    role: 'PUBLICADOR',
    canLeadPreaching: false,
    canPublicPreaching: false,
    active: true,
    createdAt: '2026-02-01T08:00:00Z',
  },
];

export const DEMO_PLACES: PreachingPlace[] = [
  {
    id: 'place-demo-01',
    congregationId: 'cong-demo-01',
    name: 'Salón del Reino',
    address: 'Av. Las Palmas #120, Col. San Benito',
    latitude: 13.6929,
    longitude: -89.2182,
    description: 'Punto principal de reunión para los fines de semana',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'place-demo-02',
    congregationId: 'cong-demo-01',
    name: 'Casa del Hno. López',
    address: 'Pje. Los Pinos, Casa 45',
    latitude: 13.6985,
    longitude: -89.2241,
    description: 'Salida de entre semana grupo 2',
    active: true,
    createdAt: '2026-01-12T08:00:00Z',
  },
  {
    id: 'place-demo-03',
    congregationId: 'cong-demo-01',
    name: 'Parque Central',
    address: 'Plaza Mayor, Centro Histórico',
    latitude: 13.699,
    longitude: -89.1914,
    description: 'Punto de partida matutino para territorio comercial',
    active: true,
    createdAt: '2026-01-15T08:00:00Z',
  },
];

export const DEMO_TERRITORIES: Territory[] = [
  {
    id: 'terr-demo-01',
    congregationId: 'cong-demo-01',
    number: '01',
    name: 'Sector Residencial Norte',
    description: 'Casas unifamiliares y pasajes peatonales',
    status: 'ASIGNADO',
    polygon: [
      { latitude: 13.702, longitude: -89.225 },
      { latitude: 13.705, longitude: -89.221 },
      { latitude: 13.701, longitude: -89.217 },
      { latitude: 13.698, longitude: -89.221 },
    ],
    active: true,
    observations: 'Zona tranquila, timbre preferente',
    lastAssignedDate: '2026-10-10',
    lastAssignedTo: 'Carlos López',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'terr-demo-02',
    congregationId: 'cong-demo-01',
    number: '02',
    name: 'Sector Comercial Centro',
    description: 'Negocios, tiendas y apartamentos sobre la avenida',
    status: 'DISPONIBLE',
    polygon: [
      { latitude: 13.698, longitude: -89.221 },
      { latitude: 13.701, longitude: -89.217 },
      { latitude: 13.696, longitude: -89.213 },
      { latitude: 13.693, longitude: -89.218 },
    ],
    active: true,
    observations: 'Predicar de preferencia en horario matutino',
    lastAssignedDate: '2026-09-28',
    lastAssignedTo: 'José Martínez',
    createdAt: '2026-01-02T08:00:00Z',
  },
  {
    id: 'terr-demo-03',
    congregationId: 'cong-demo-01',
    number: '03',
    name: 'Colonia Los Laureles',
    description: 'Zona de colina con calles empinadas',
    status: 'DISPONIBLE',
    polygon: [
      { latitude: 13.693, longitude: -89.218 },
      { latitude: 13.696, longitude: -89.213 },
      { latitude: 13.691, longitude: -89.21 },
      { latitude: 13.688, longitude: -89.215 },
    ],
    active: true,
    observations: 'Buen acceso vehicular en la entrada',
    lastAssignedDate: '2026-09-15',
    lastAssignedTo: 'Juan Pérez',
    createdAt: '2026-01-03T08:00:00Z',
  },
];

export const DEMO_WEEKLY_ASSIGNMENTS: WeeklyAssignment[] = [
  {
    id: 'week-demo-01',
    congregationId: 'cong-demo-01',
    date: '2026-10-10',
    time: '08:00',
    placeId: 'place-demo-01',
    placeName: 'Salón del Reino',
    leaderId: 'user-demo-coord',
    leaderName: 'Carlos López',
    territoryId: 'terr-demo-01',
    territoryNumber: '01',
    notes: 'Salida de congregación de sábado matutina.',
    hasConflict: false,
    createdAt: '2026-10-01T10:00:00Z',
    createdBy: 'user-demo-coord',
  },
  {
    id: 'week-demo-02',
    congregationId: 'cong-demo-01',
    date: '2026-10-11',
    time: '09:00',
    placeId: 'place-demo-03',
    placeName: 'Parque Central',
    leaderId: 'user-demo-pub1',
    leaderName: 'Juan Pérez',
    territoryId: 'terr-demo-02',
    territoryNumber: '02',
    notes: 'Salida dominical después del discurso.',
    hasConflict: false,
    createdAt: '2026-10-02T10:00:00Z',
    createdBy: 'user-demo-coord',
  },
  {
    id: 'week-demo-03',
    congregationId: 'cong-demo-01',
    date: '2026-10-14',
    time: '16:00',
    placeId: 'place-demo-02',
    placeName: 'Casa del Hno. López',
    leaderId: 'user-demo-super',
    leaderName: 'José Martínez',
    territoryId: 'terr-demo-03',
    territoryNumber: '03',
    notes: 'Predicación vespertina de miércoles.',
    hasConflict: false,
    createdAt: '2026-10-03T10:00:00Z',
    createdBy: 'user-demo-super',
  },
];

export const DEMO_PUBLIC_PLACES: PublicPreachingPlace[] = [
  {
    id: 'pub-place-01',
    congregationId: 'cong-demo-01',
    name: 'Parque Central (Frente a Catedral)',
    address: 'Plaza Cívica Central',
    latitude: 13.6992,
    longitude: -89.1916,
    day: 'Sábado',
    time: '09:00',
    duration: '2 horas',
    description: 'Punto de exhibidor rodante de alto tránsito',
    active: true,
    fixedMemberIds: ['user-demo-coord'],
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'pub-place-02',
    congregationId: 'cong-demo-01',
    name: 'Estación de Autobuses Terminal Sur',
    address: 'Entrada principal pasarela peatonal',
    latitude: 13.6821,
    longitude: -89.2014,
    day: 'Domingo',
    time: '08:30',
    duration: '2.5 horas',
    description: 'Exhibidor con publicaciones multilingües',
    active: true,
    fixedMemberIds: ['user-demo-super', 'user-demo-pub2'],
    createdAt: '2026-01-15T08:00:00Z',
  },
];

export const DEMO_PUBLIC_ASSIGNMENTS: PublicPreachingAssignment[] = [
  {
    id: 'pub-assign-01',
    congregationId: 'cong-demo-01',
    placeId: 'pub-place-01',
    placeName: 'Parque Central (Frente a Catedral)',
    date: '2026-10-10',
    time: '09:00',
    participants: [
      { userId: 'user-demo-coord', userName: 'Carlos López', isFixed: true },
      { userId: 'user-demo-pub1', userName: 'Juan Pérez', isFixed: false },
    ],
    notes: 'Llevar exhibidor A y folletos recién recibidos',
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'pub-assign-02',
    congregationId: 'cong-demo-01',
    placeId: 'pub-place-02',
    placeName: 'Estación de Autobuses Terminal Sur',
    date: '2026-10-11',
    time: '08:30',
    participants: [
      { userId: 'user-demo-super', userName: 'José Martínez', isFixed: true },
      { userId: 'user-demo-pub2', userName: 'Pedro Hernández', isFixed: true },
      { userId: 'user-demo-pub1', userName: 'Juan Pérez', isFixed: false },
    ],
    notes: 'Exhibidor B con revistas del mes',
    createdAt: '2026-10-02T10:00:00Z',
  },
];
